#!/bin/sh

set -eux

mydir="${0%/*}"
fix_verity_efi="${mydir}/fix-verity.efi"

# hihi fakeroot
unset LD_PRELOAD

if [ ! -f ${fix_verity_efi} ]; then
    if ! podman image exists quay.io/lis/fix-verity; then
        podman image build -t quay.io/lis/fix-verity "${mydir}"
    fi

    podman run --rm -i quay.io/lis/fix-verity \
        cat /fix-verity.efi > "${fix_verity_efi}".tmp
    mv "${fix_verity_efi}.tmp" "${fix_verity_efi}"
fi

ovmf=""
for p in /usr/share/OVMF/OVMF_CODE.fd /usr/share/ovmf/OVMF.fd /usr/share/edk2/ovmf/OVMF_CODE.fd /usr/share/edk2/x64/OVMF.4m.fd; do
    if [ -f "$p" ]; then ovmf="$p"; break; fi
done
[ -n "$ovmf" ] || { echo "Cannot find OVMF firmware"; exit 1; }

qemu-system-x86_64 \
    -nographic \
    -m 4096 \
    -enable-kvm \
    -machine q35 \
    -bios "${ovmf}" \
    -drive file="$1",format=raw,if=virtio,media=disk \
    -kernel "${fix_verity_efi}"
